version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    cooldown:
      default-days: 2
    groups:
      angular:
        patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'angular-eslint'
          - 'rxjs'
      other:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'angular-eslint'
          - 'rxjs'
        update-types:
          - 'minor'
          - 'patch'
      other-major:
        patterns:
          - '*'
        exclude-patterns:
          - '@angular/*'
          - '@angular-devkit/*'
          - '@schematics/angular'
          - 'angular-eslint'
          - 'rxjs'
        update-types:
          - 'major'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      actions:
        patterns:
          - '*'
