/**
 * Content build script entry point.
 *
 * Processes markdown files from src/content/{blog,talks,projects,pages}/
 * and generates typed TypeScript manifests in src/app/content/*.generated.ts.
 *
 * Run via: npx tsx scripts/build-content.ts
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

import {
  createDuplicateTracker,
  isDuplicateSlug,
  parseBlogPost,
  parseProject,
  parseTalk,
} from './frontmatter';
import { disposeHighlighter, renderMarkdown } from './markdown';

import type { BlogPost, Project, Talk } from '../src/app/models/content.model';

const ROOT_DIR = resolve(import.meta.dirname, '..');
const CONTENT_DIR = join(ROOT_DIR, 'src', 'content');
const OUTPUT_DIR = join(ROOT_DIR, 'src', 'app', 'content');

/**
 * Scans a directory for .md files and returns their full paths.
 * Returns an empty array if the directory doesn't exist.
 */
function scanMarkdownFiles(dir: string): string[] {
  if (!existsSync(dir)) {
    console.log(`[build-content] Directory not found: ${dir} — producing empty manifest.`);
    return [];
  }

  return readdirSync(dir)
    .filter((file) => file.endsWith('.md'))
    .map((file) => join(dir, file));
}

/**
 * Processes all blog posts: parse frontmatter, render markdown, exclude drafts.
 */
async function processBlogPosts(): Promise<BlogPost[]> {
  const dir = join(CONTENT_DIR, 'blog');
  const files = scanMarkdownFiles(dir);
  const tracker = createDuplicateTracker();
  const posts: BlogPost[] = [];

  for (const filePath of files) {
    const post = parseBlogPost(filePath);
    if (!post) continue;

    // Exclude drafts
    if (post.draft) continue;

    // Check for duplicate slugs
    if (isDuplicateSlug(tracker, post.slug, filePath)) continue;

    // Render markdown content
    const { html, headings } = await renderMarkdown(post.content);
    post.content = html;
    post.headings = headings;

    posts.push(post);
  }

  // Sort by created date descending (newest first)
  posts.sort((a, b) => b.created.localeCompare(a.created));

  return posts;
}

/**
 * Processes all talks: parse frontmatter, render markdown, exclude drafts.
 */
async function processTalks(): Promise<Talk[]> {
  const dir = join(CONTENT_DIR, 'talks');
  const files = scanMarkdownFiles(dir);
  const tracker = createDuplicateTracker();
  const talks: Talk[] = [];

  for (const filePath of files) {
    const talk = parseTalk(filePath);
    if (!talk) continue;

    // Exclude drafts
    if (talk.draft) continue;

    // Check for duplicate slugs
    if (isDuplicateSlug(tracker, talk.slug, filePath)) continue;

    // Render markdown content
    const { html } = await renderMarkdown(talk.content);
    talk.content = html;

    talks.push(talk);
  }

  // Sort by date descending (newest first)
  talks.sort((a, b) => b.date.localeCompare(a.date));

  return talks;
}

/**
 * Processes all projects: parse frontmatter, render markdown, exclude drafts.
 */
async function processProjects(): Promise<Project[]> {
  const dir = join(CONTENT_DIR, 'projects');
  const files = scanMarkdownFiles(dir);
  const tracker = createDuplicateTracker();
  const projects: Project[] = [];

  for (const filePath of files) {
    const project = parseProject(filePath);
    if (!project) continue;

    // Exclude drafts (status === 'draft')
    if (project.status === 'draft') continue;

    // Check for duplicate slugs
    if (isDuplicateSlug(tracker, project.slug, filePath)) continue;

    // Render markdown content
    const { html } = await renderMarkdown(project.content);
    project.content = html;

    projects.push(project);
  }

  // Sort by created date descending (newest first)
  projects.sort((a, b) => b.created.localeCompare(a.created));

  return projects;
}

/**
 * Writes a generated TypeScript file with the given content array.
 */
function writeGeneratedFile(
  filename: string,
  typeName: string,
  variableName: string,
  items: unknown[],
): void {
  const importPath = typeName === 'BlogPost' || typeName === 'Talk' || typeName === 'Project'
    ? `'../models/content.model'`
    : `'../models/content.model'`;

  const serializedItems = items
    .map((item) => `  ${JSON.stringify(item)}`)
    .join(',\n');

  const content = `// Auto-generated by build-content script. Do not edit manually.
import type { ${typeName} } from ${importPath};

export const ${variableName}: ${typeName}[] = [
${serializedItems}${items.length > 0 ? ',' : ''}
];
`;

  const filePath = join(OUTPUT_DIR, filename);
  writeFileSync(filePath, content, 'utf-8');
}

async function buildContent(): Promise<void> {
  console.log('Content build starting...');

  // Ensure output directory exists
  if (!existsSync(OUTPUT_DIR)) {
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Process all content types
  const [blogPosts, talks, projects] = await Promise.all([
    processBlogPosts(),
    processTalks(),
    processProjects(),
  ]);

  // Write generated TypeScript files
  writeGeneratedFile('blog-posts.generated.ts', 'BlogPost', 'BLOG_POSTS', blogPosts);
  writeGeneratedFile('talks.generated.ts', 'Talk', 'TALKS', talks);
  writeGeneratedFile('projects.generated.ts', 'Project', 'PROJECTS', projects);

  // Clean up highlighter resources
  await disposeHighlighter();

  console.log(
    `Content build complete. Generated ${blogPosts.length} blog posts, ${talks.length} talks, ${projects.length} projects.`,
  );
}

buildContent().catch((error: unknown) => {
  console.error('Content build failed:', error);
  process.exit(1);
});
