import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { JSDOM } from 'jsdom';

const ROOT_DIR = resolve(import.meta.dirname, '..');
const DIST_DIR = join(ROOT_DIR, 'dist', 'k9n-dev', 'browser');

/**
 * Unit tests for the root-level redirect page (index.html).
 * These tests verify the generated HTML structure and redirect logic.
 *
 * Note: The redirect page is generated by `scripts/post-build.ts` during the build.
 * For unit testing, we generate the HTML inline and validate its structure.
 */

/** Generate the redirect HTML matching what post-build.ts produces */
function getRedirectHtml(): string {
  return `<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>k9n.dev — Redirecting…</title>
  <script>
    (function() {
      var SUPPORTED = ['de', 'en'];
      var DEFAULT = 'de';

      function getStoredLocale() {
        try {
          var stored = localStorage.getItem('k9n-preferred-locale');
          if (stored && SUPPORTED.indexOf(stored) !== -1) {
            return stored;
          }
        } catch (e) {
          // localStorage unavailable (private browsing, SecurityError)
        }
        return null;
      }

      function detectBrowserLocale() {
        var languages = (navigator.languages && navigator.languages.length)
          ? navigator.languages
          : [navigator.language || ''];

        for (var i = 0; i < languages.length; i++) {
          var lang = languages[i].toLowerCase();
          for (var j = 0; j < SUPPORTED.length; j++) {
            if (lang === SUPPORTED[j] || lang.indexOf(SUPPORTED[j] + '-') === 0) {
              return SUPPORTED[j];
            }
          }
        }
        return null;
      }

      var locale = getStoredLocale() || detectBrowserLocale() || DEFAULT;
      var path = window.location.pathname;

      // Preserve any sub-path after the root (e.g., /blog → /de/blog)
      var subPath = path === '/' ? '/' : path;
      var target = '/' + locale + subPath;

      // Avoid double slashes
      target = target.replace(/\\/\\/+/g, '/');

      window.location.replace(target);
    })();
  </script>
  <noscript>
    <meta http-equiv="refresh" content="0; url=/de/">
  </noscript>
</head>
<body>
  <p>Redirecting…</p>
</body>
</html>
`;
}

describe('Redirect page (root index.html)', () => {
  const html = getRedirectHtml();

  it('should be a valid HTML document with lang="de"', () => {
    expect(html).toContain('<!DOCTYPE html>');
    expect(html).toContain('<html lang="de">');
  });

  it('should contain a <title> element', () => {
    expect(html).toMatch(/<title>[^<]+<\/title>/);
  });

  it('should check localStorage for "k9n-preferred-locale" key', () => {
    expect(html).toContain("localStorage.getItem('k9n-preferred-locale')");
  });

  it('should validate stored locale against supported locales', () => {
    expect(html).toContain("SUPPORTED.indexOf(stored) !== -1");
  });

  it('should handle localStorage errors gracefully (private browsing)', () => {
    expect(html).toContain('catch (e)');
    expect(html).toContain('localStorage unavailable');
  });

  it('should detect browser locale from navigator.languages', () => {
    expect(html).toContain('navigator.languages');
  });

  it('should fall back to navigator.language when languages is empty', () => {
    expect(html).toContain('navigator.language');
  });

  it('should support "de" and "en" as valid locales', () => {
    expect(html).toContain("var SUPPORTED = ['de', 'en']");
  });

  it('should default to "de" when no match is found', () => {
    expect(html).toContain("var DEFAULT = 'de'");
    expect(html).toContain('|| DEFAULT');
  });

  it('should use window.location.replace for redirect (no history entry)', () => {
    expect(html).toContain('window.location.replace(target)');
  });

  it('should provide a noscript fallback redirecting to /de/', () => {
    const dom = new JSDOM(html);
    const noscript = dom.window.document.querySelector('noscript');
    expect(noscript).not.toBeNull();
    const meta = noscript!.querySelector('meta[http-equiv="refresh"]');
    expect(meta).not.toBeNull();
    expect(meta!.getAttribute('content')).toBe('0; url=/de/');
  });

  it('should match regional language variants (e.g., "de-AT", "en-US")', () => {
    expect(html).toContain("lang.indexOf(SUPPORTED[j] + '-') === 0");
  });

  describe('redirect logic simulation', () => {
    function simulateRedirect(options: {
      storedLocale?: string | null;
      languages?: string[];
      pathname?: string;
    }): string {
      const { storedLocale = null, languages = [], pathname = '/' } = options;
      const SUPPORTED = ['de', 'en'];
      const DEFAULT = 'de';

      function getStoredLocale(): string | null {
        try {
          if (storedLocale && SUPPORTED.indexOf(storedLocale) !== -1) {
            return storedLocale;
          }
        } catch {
          // localStorage unavailable
        }
        return null;
      }

      function detectBrowserLocale(): string | null {
        const langs = languages.length ? languages : [''];
        for (let i = 0; i < langs.length; i++) {
          const lang = langs[i].toLowerCase();
          for (let j = 0; j < SUPPORTED.length; j++) {
            if (lang === SUPPORTED[j] || lang.indexOf(SUPPORTED[j] + '-') === 0) {
              return SUPPORTED[j];
            }
          }
        }
        return null;
      }

      const locale = getStoredLocale() || detectBrowserLocale() || DEFAULT;
      const subPath = pathname === '/' ? '/' : pathname;
      let target = '/' + locale + subPath;
      target = target.replace(/\/\/+/g, '/');
      return target;
    }

    it('should redirect to /en/ when stored locale is "en"', () => {
      expect(simulateRedirect({ storedLocale: 'en' })).toBe('/en/');
    });

    it('should redirect to /de/ when stored locale is "de"', () => {
      expect(simulateRedirect({ storedLocale: 'de' })).toBe('/de/');
    });

    it('should ignore invalid stored locale and fall back to browser detection', () => {
      expect(simulateRedirect({ storedLocale: 'fr', languages: ['en-US'] })).toBe('/en/');
    });

    it('should detect "en" from navigator.languages ["en-US", "de"]', () => {
      expect(simulateRedirect({ languages: ['en-US', 'de'] })).toBe('/en/');
    });

    it('should detect "de" from navigator.languages ["de-AT", "en"]', () => {
      expect(simulateRedirect({ languages: ['de-AT', 'en'] })).toBe('/de/');
    });

    it('should default to /de/ when no language matches', () => {
      expect(simulateRedirect({ languages: ['fr', 'ja', 'es'] })).toBe('/de/');
    });

    it('should default to /de/ with empty navigator.languages', () => {
      expect(simulateRedirect({ languages: [] })).toBe('/de/');
    });

    it('should preserve stored preference over browser language', () => {
      expect(simulateRedirect({ storedLocale: 'de', languages: ['en-US'] })).toBe('/de/');
    });

    it('should default to /de/ when localStorage is unavailable (null stored)', () => {
      expect(simulateRedirect({ storedLocale: null, languages: ['fr'] })).toBe('/de/');
    });
  });
});
