name: Build and eventually deploy

on:
  push:
    branches:
      - '*'

env:
  TARGET_DIR: dist/analog/public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set environment variable based on branch
        run: |
          if [[ $GITHUB_REF == refs/heads/main || $GITHUB_REF == refs/heads/master ]]; then
            echo "Branch is main or master. Setting DRY_RUN to empty."
            echo "DRY_RUN=" >> $GITHUB_ENV
          else
            echo "Branch is not main or master. Setting DRY_RUN to '--dry-run'."
            echo "DRY_RUN=--dry-run" >> $GITHUB_ENV
          fi
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'UA-XXXXXXXXX-1'
          replace: ${{ secrets.G_TAG_CODE }}
          include: 'vite.config.ts' # Replace google Tag
      - name: Install
        run: |
          npm config set legacy-peer-deps true
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Deploy Website (gh-pages branch)
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_REPO: https://github.com/d-koppenhagen/k9n.dev.git
          GITHUB_NAME: Danny Koppenhagen
          GITHUB_EMAIL: mail@k9n.dev
        run: |
          echo "DRY_RUN=$DRY_RUN"
          npx angular-cli-ghpages --cname=k9n.dev --no-silent --dir="${{env.TARGET_DIR}}" --repo="$GITHUB_REPO" --name="$GITHUB_NAME" --email="$GITHUB_EMAIL" $DRY_RUN
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: public dir
          path: ${{env.TARGET_DIR}}
