# This is a basic workflow to help you get started with Actions

name: GH Pages Re-Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
    branches:
      - gh-pages

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Re-Deploy GH Pages by empty commit
        run: |
          git config --global user.name 'Danny Koppenhagen'
          git config --global user.email 'mail@k9n.dev'
          git commit --allow-empty -m "Empty commit (re-deploy)"
          git push
