name: Sync-to-devto

on:
  workflow_dispatch:

jobs:
  sync-devto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'DEVTO_API_KEY'
          replace: ${{ secrets.DEVTO_API_KEY }}
          include: 'scripts/devto-update.js' # Replace with real API Key
      - run: cd scripts && npm ci && node devto-update.js
