name: Sync-to-devto

on:
  workflow_dispatch:

jobs:
  sync-devto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: '22.x'

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: 'DEVTO_API_KEY'
          replace: ${{ secrets.DEVTO_API_KEY }}
          include: 'scripts/devto-update.js' # Replace with real API Key

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run devto update
        working-directory: scripts
        run: node devto-update.js
